liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        news_thumb:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [400, 220], mode: outbound }
                # no format filter
        
        news_list_thumb:
            quality: 75
            filters:
                thumbnail: { size: [185, 105], mode: outbound }
                # no format filter

        news_large:
            quality: 85
            filters:
                thumbnail: { size: [1280, 720], mode: inset }
                # no format filter

                
        admin_thumb:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

        doctor_thumb:
            quality: 80
            filters:
                thumbnail: { size: [300, 400], mode: outbound }

        hero:
            quality: 75
            filters:
                thumbnail: { size: [1920, 1080], mode: outbound }
                # no format filter

        hero_mobile:
            quality: 75
            filters:
                thumbnail: { size: [600, 800], mode: outbound }
                # no format filter

        service_card:
            quality: 75
            filters:
                thumbnail: { size: [600, 400], mode: outbound }
                # no format filter

        about_image:
            quality: 75
            filters:
                thumbnail: { size: [800, 800], mode: outbound }
                # no format filter

        about_home:
            quality: 75
            filters:
                thumbnail: { size: [448, 450], mode: outbound }
                # no format filter


        page_header:
            quality: 75
            filters:
                thumbnail: { size: [1920, 600], mode: outbound }
                # no format filter

        service_detail:
            quality: 75
            filters:
                thumbnail: { size: [800, 600], mode: inset }
                # no format filter
