twig:
    file_name_pattern: '*.twig'
    form_themes: ['form/tailwind_glass_theme.html.twig']
    globals:
        templateService: '@App\Service\TemplateService'

when@test:
    twig:
        strict_variables: true
