vich_uploader:
    db_driver: orm

    mappings:
        news_image:
            uri_prefix: /images/news
            upload_destination: '%kernel.project_dir%/public/images/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        service_image:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        doctor_image:
            uri_prefix: /images/team
            upload_destination: '%kernel.project_dir%/public/images/team'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        transparency_file:
            uri_prefix: /files/transparency
            upload_destination: '%kernel.project_dir%/public/files/transparency'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        timeline_image:
            uri_prefix: /images/timeline
            upload_destination: '%kernel.project_dir%/public/images/timeline'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        banner_image:
            uri_prefix: /images/banners
            upload_destination: '%kernel.project_dir%/public/images/banners'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        about_image:
            uri_prefix: /images/about
            upload_destination: '%kernel.project_dir%/public/images/about'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        specialty_image:
            uri_prefix: /images/specialties
            upload_destination: '%kernel.project_dir%/public/images/specialties'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
